version: "3"
services:
  web:
    image: nargyanti/uas-cloud:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/laravel
    version: "3"
  web-2:
    image: nargyanti/uas-cloud-2:latest
    container_name: web-2
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/laravel